---

kind: pipeline
type: docker

steps:
  - name: fetch git tags
    image: alpine/git
    commands:
      - git fetch --tags

  - name: restore cache
    image: drillster/drone-volume-cache
    volumes:  # mount the cache volume, needs "Trusted"
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - dev/builder/ckbuilder

  - name: tests
    image: openjdk:12
    commands:
      - yum -y install git
      - dev/builder/build.sh

  - name: create draft release
    image: plugins/github-release
    settings:
      draft: true
      files: dev/builder/release/ckeditor_${DRONE_TAG}.tar.gz
      checksum:
        - sha256
      api_key:
        from_secret: github_token
    when:
      event: tag

  - name: publish release
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
    when:
      event: tag

  - name: rebuild cache
    image: drillster/drone-volume-cache
    volumes:  # mount the cache volume, needs "Trusted"
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - dev/builder/ckbuilder

volumes:
  - name: cache
    host:
      path: /tmp/cache
